[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[project]
name = "{{ cookiecutter.project_name }}"
version = "0.1.0"
description = "{{ cookiecutter.project_short_description }}"
readme = "README.md"
requires-python = ">={{ cookiecutter.python_version }}"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}" },
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: {{ cookiecutter.python_version.split('.')[0] }}",
  "Programming Language :: Python :: {{ cookiecutter.python_version }}",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  # Add your project-specific runtime dependencies here
]

[project.scripts]
{{ cookiecutter.project_name }} = "{{ cookiecutter.project_slug }}.main:main"

[project.urls]
Documentation = "https://github.com/{{ cookiecutter.user_name }}/{{ cookiecutter.project_name }}#readme"
Issues = "https://github.com/{{ cookiecutter.user_name }}/{{ cookiecutter.project_name }}/issues"
Source = "https://github.com/{{ cookiecutter.user_name }}/{{ cookiecutter.project_name }}"

[dependency-groups]
dev = [
  "mypy",
  "pytest",
  "pytest-cov",
  "pytest-randomly",
  "ruff",
]

[tool.coverage.run]
source_pkgs = ["{{ cookiecutter.project_slug }}", "tests"]
branch = true
parallel = true

[tool.coverage.paths]
"{{ cookiecutter.project_slug }}" = [
  "src/{{ cookiecutter.project_slug }}",
  "*/{{ cookiecutter.project_name }}/src/{{ cookiecutter.project_slug }}",
]
tests = ["tests", "*/{{ cookiecutter.project_slug }}/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
line-length = 89
target-version = "py{{ cookiecutter.python_version.replace('.', '') }}"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle error
  "W",   # pycodestyle warning
  "F",   # Pyflakes
  "I",   # isort
  "N",   # pep8-naming
  "D",   # pydocstyle
  "UP",  # pyupgrade
  "S",   # flake8-bandit
  "B",   # flake8-bugbear
  "A",   # flake8-builtins
  "C4",  # flake8-comprehensions
  "T20", # flake8-print
  "PTH", # flake8-pathlib
  "PIE", # flake8-pie
  "RSE", # flake8-raise
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "ANN", # flake8-annotations
]
ignore = [
  "D100", "D104", "D105", "D106", "D107", "D203", "D213", "D406", "D407", # Docstring rules
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "S101", # flake8-bandit: use of assert
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
python_version = "{{ cookiecutter.python_version }}"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
